### PR TITLE
Fightstick/arcade branch

### PR DESCRIPTION
**Pull request by CrazyRedMachine**
Hi,
Stumbled upon your thread on reddit /r/cade, this is great work :) Thanks for making it, and most importantly for sharing it.
I did a couple changes for it to be used on my arcade cabinet (there's only one joystick, so I implemented a mode switch using button combos so you can select if joystick is LeftAnalog, DPAD or RightAnalog... I also used one of the freed pins to have a HOME button, and moved L3/R3 to button combos since their use is rare... 

I think that variant can be useful for people building their own arcade cabinet or fightsticks, so it could warrant a new branch :)

Thanks,

### CODE REVIEW

**Comment by bootsector** [comment]
Hi there!

Thanks for your time on this! I hope this code has met your needs and that you are having tons of fun with your custom made XInput based arcade controller! :)

I've published this firmware in its simplest form so it can also serve as a template for people who would like to tinker with it and add new features. I believe that not adding any sorts of "combos" or any personal mapping preferences on it would make the code cleaner and easier to follow. 

In this sense, although your pull request contain lots of neat features, I will be declining it for the sake of keeping the simplicity of this code.

Please, feel free to open a fork with your customizations, since I'm pretty sure there are lots of people interested on what you've done here!

Cheers,

bootsector

**Comment by CrazyRedMachine** [comment]
Hi,

Doesn't start+back for home count as a button combo ?

I reckon the combos used in my branch are not intuitive, so I thought we might simplify them to start+left (left analog), start+up (dpad), start+right (right analog)..

Btw, do you plan on including xinput lights in the future ?

Thanks,

**Comment by bootsector** [comment]
Oh, right, so there *IS* one combo! Almost forgot that bastard! :P

I don't plan to develop this firmware any further. As I've mentioned before, I'm leaving this as a template so people can create more elaborate projects based on it.

Feel free to fork it and have lots of fun! :)

**Comment by CrazyRedMachine** [comment]
lol ok, i might add these in the future then :) thanks a lot for the template!

**Pull request closed without merging**
